import { Api } from './api/api';
import type { Car, Winner } from './types';
import { HeaderFactory } from './components/ui/layout/Header';
import { MainFactory } from './components/ui/layout/Main';
import { GarageView } from './components/views/Garage-view';
import { WinnersView } from './components/views/Winners-view';
import { Garage } from './components/cars/Garage';
import { CarTransform } from './components/ui/car-transform/Car-transform';
import { Pagination } from './components/pagination/Pagination';
import { Winners } from './components/cars/Winners';
import { ErrorNotification } from './components/ui/error-notification/Error-notification';
import { Router } from './components/router/router';
import './styles/modern-normalize.css';
import './styles/style.css';

export const RANDOM_CAR_COLORS = [
  '#095387',
  '#0c65d9',
  '#0ca8d4',
  '#39c778',
  '#40cdba',
  '#435bc8',
  '#48a4d9',
  '#58da23',
  '#5c18cd',
  '#5d4a40',
  '#5eb25e',
  '#61acfe',
  '#62a193',
  '#6424ff',
  '#6e88d7',
  '#79ac6b',
  '#7a5fe4',
  '#7e420c',
  '#818164',
  '#9ddd97',
  '#a8e0f3',
  '#abf3cf',
  '#bce6ca',
  '#d1ed1e',
  '#d2ceb6',
  '#d87325',
  '#e03f7b',
  '#e821c8',
  '#f48c3c',
  '#fe2286',
  '#4ce0f0',
  '#94317f',
  '#8600b4',
  '#1e6153',
  '#3ef08c',
  '#f8daae',
  '#991e3f',
  '#d5fe5d',
  '#d0eb41',
  '#f9da52',
  '#e13ba7',
  '#ebd5aa',
  '#3e6b70',
  '#8d1697',
  '#78fc07',
  '#7747fa',
  '#f6d449',
  '#005fb8',
  '#2fa48f',
  '#46e712',
  '#45afc4',
  '#03fc58',
  '#d87314',
  '#2824ef',
  '#d578fe',
  '#83928d',
  '#1c0f5c',
  '#daeab2',
  '#1a90b4',
  '#ae4b5e',
  '#3f9c33',
  '#78337d',
  '#03abe7',
  '#9503ef',
  '#3b9cdb',
  '#154d5a',
  '#aeaca3',
  '#ebaa8a',
  '#74f294',
  '#1ea666',
  '#ced0f9',
  '#da3904',
  '#61030c',
  '#164382',
  '#121e9c',
  '#2a58d7',
  '#1b5fcf',
  '#7a9fb9',
  '#fdffc2',
  '#081a6f',
  '#61c749',
  '#401e98',
  '#9ecf2c',
  '#d27c3a',
  '#7c5917',
  '#44496b',
  '#ee1b9f',
  '#32262e',
  '#92fefd',
  '#61d56a',
  '#2c4fda',
  '#0bc7b7',
  '#56e971',
  '#920032',
  '#816e9e',
  '#631d60',
  '#5579fd',
  '#fdda50',
  '#c8a181',
  '#e0b19f',
];

export const RANDOM_CAR_MODELS = [
  'TLX',
  'Giulia',
  'Atom',
  'DB11',
  'A4',
  'Continental GT',
  '3 Series',
  'V5',
  'Chiron',
  'Enclave',
  'Song',
  'Escalade',
  'CT660',
  'CS75',
  'Tiggo 7 Pro',
  'Silverado',
  '300',
  'C3',
  'Matiz',
  'XF',
  'Terios',
  'GO',
  'Ram 1500',
  'AX7',
  'DS 7 Crossback',
  'TXL',
  'FF 91',
  '488 GTB',
  '500',
  'Ocean',
  'F-Series',
  'GS4',
  'Emgrand',
  'G80',
  'Sierra',
  'Haval H6',
  'S5',
  'Jolion',
  'Civic',
  'H2',
  'Tucson',
  'Q50',
  'D-Max',
  'S3',
  'F-PACE',
  'Grand Cherokee',
  'E5',
  'Sportage',
  'Jesko',
  'Huracán',
  'Ypsilon',
  'Range Rover',
  'RX',
  'X60',
  'Navigator',
  'Air',
  'U6',
  'Ghibli',
  'S-Class',
  'CX-5',
  'C-Class',
  'Grand Marquis',
  'Cooper',
  'Outlander',
  'Qashqai',
  'C5',
  'Cutlass',
  'Corsa',
  'Huayra',
  '208',
  'Myvi',
  'Battista',
  'Firebird',
  '911',
  'Saga',
  'R2',
  'Clio',
  'Nevera',
  'Phantom',
  '75',
  '45903',
  'S7',
  'tC',
  'Leon',
  'Octavia',
  'Fortwo',
  'C8',
  'Rexton',
  'Outback',
  'Swift',
  '300',
  'Nexon',
  'Model 3',
  'Corolla',
  'W8',
  'VF8',
  'Golf',
  'XC60',
  'MF5',
  'T600',
];

export const RANDOM_CAR_BRANDS = [
  'Acura',
  'Alfa Romeo',
  'Ariel',
  'Aston Martin',
  'Audi',
  'Bentley',
  'BMW',
  'Brilliance',
  'Bugatti',
  'Buick',
  'BYD',
  'Cadillac',
  'Caterpillar',
  'Changan',
  'Chery',
  'Chevrolet',
  'Chrysler',
  'Citroen',
  'Daewoo',
  'DAF',
  'Daihatsu',
  'Datsun',
  'Dodge',
  'DongFeng',
  'DS',
  'Exeed',
  'Faraday Future',
  'Ferrari',
  'Fiat',
  'Fisker',
  'Ford',
  'GAC',
  'Geely',
  'Genesis',
  'GMC',
  'Great Wall',
  'Haima',
  'Haval',
  'Honda',
  'Hummer',
  'Hyundai',
  'Infiniti',
  'Isuzu',
  'JAC',
  'Jaguar',
  'Jeep',
  'Kaiyi',
  'Kia',
  'Koenigsegg',
  'Lamborghini',
  'Lancia',
  'Land Rover',
  'Lexus',
  'Lifan',
  'Lincoln',
  'Lucid',
  'Luxgen',
  'Maserati',
  'Maybach',
  'Mazda',
  'Mercedes-Benz',
  'Mercury',
  'Mini',
  'Mitsubishi',
  'Nissan',
  'Omoda',
  'Oldsmobile',
  'Opel',
  'Pagani',
  'Peugeot',
  'Perodua',
  'Pininfarina',
  'Pontiac',
  'Porsche',
  'Proton',
  'Ravon',
  'Renault',
  'Rimac',
  'Rolls-Royce',
  'Rover',
  'Saab',
  'Saleen',
  'Scion',
  'SEAT',
  'Skoda',
  'Smart',
  'Spyker',
  'SsangYong',
  'Subaru',
  'Suzuki',
  'Tank',
  'Tata',
  'Tesla',
  'Toyota',
  'Vector',
  'VinFast',
  'Volkswagen',
  'Volvo',
  'Wiesmann',
  'Zotye',
];

export const errorNotification = new ErrorNotification();
export const garage = new Garage();
export const winners = new Winners();
export const pagination = new Pagination(7);
export const carTransform = new CarTransform();
export const garageApi = new Api<Car>('garage');
export const winnersApi = new Api<Winner>('winners');

export const main = MainFactory.get();

export const garageView = new GarageView();
export const garageViewSection = garageView.section;

export const winnersView = new WinnersView();
export const winnersViewSection = winnersView.section;

document.body.append(HeaderFactory.get(), main);

Router.addRoute('/', () => {
  garageView.open();
});

Router.addRoute('/garage', () => {
  garageView.open();
});

Router.addRoute('/winners', () => {
  winnersView.open();
});

Router.init();
